"""Framework layer (CTAF US-16): manifest checking, policy and plan control.

US-16-AC-1 ships the manifest-checker; US-16-AC-2 ships Policy abstractions,
Plan/L18 white-list rules, the eight-state lifecycle (L19) and
``validate_plan``.  The layer follows CTAF v0.4.1
(``docs/plans/distributed-agent-framework/design-proposal.md``).
"""

from .manifest_checker import (
    AUDIT_PROJECTION_KEYS,
    AgentManifest,
    ManifestCheckInput,
    ManifestCheckResult,
    ManifestRegistry,
    ManifestValidationError,
    check,
)
from .capability import (
    CAPABILITY_CLOSED_SET,
    CapabilityEntry,
    CapabilityKind,
    CapabilityValidationError,
    capability_entry,
    check_consistency,
    consistency_report,
    manifest_capability_allowed,
    orphan_agent_capabilities,
    resolve_capability,
    unmapped_mvp_capabilities,
)
from .lifecycle import LifecycleState, can_transition, validate_transition_path
from .memory import (
    MEMORY_PROJECTION_KEYS,
    MemoryKind,
    MemoryRecord,
    MemoryValidationError,
    MemoryWriteResult,
    canonical_record_bytes,
    record_fingerprint,
    redact_record,
    validate_record,
    write_memory,
)
from .plan import (
    POLICY_OWNED_NUMERIC_KEYS,
    Plan,
    PlanEdge,
    PlanNode,
    PlanNodeKind,
    plan_fingerprint,
)
from .tools import (
    MCP_KEYS,
    SCHEMA_KEYS,
    SCHEMA_TYPES,
    Tool,
    ToolRegistry,
    ToolSideEffect,
    ToolValidationError,
    canonical_descriptor_bytes,
    canonical_schema_bytes,
    mcp_to_tool,
    tool_to_mcp,
    validate_schema,
    validate_tool,
)
from .policy import (
    PROFILES,
    Policy,
    PolicyValidationError,
    default_profiles,
    get_default_profile,
    validate_policy,
)
from .validation import (
    VALIDATION_PROJECTION_KEYS,
    ValidationResult,
    validate_plan,
)

__all__ = [
    "AUDIT_PROJECTION_KEYS",
    "AgentManifest",
    "CAPABILITY_CLOSED_SET",
    "CapabilityEntry",
    "CapabilityKind",
    "CapabilityValidationError",
    "LifecycleState",
    "MEMORY_PROJECTION_KEYS",
    "ManifestCheckInput",
    "ManifestCheckResult",
    "ManifestRegistry",
    "ManifestValidationError",
    "MemoryKind",
    "MemoryRecord",
    "MemoryValidationError",
    "MemoryWriteResult",
    "POLICY_OWNED_NUMERIC_KEYS",
    "PROFILES",
    "Plan",
    "PlanEdge",
    "PlanNode",
    "PlanNodeKind",
    "Policy",
    "PolicyValidationError",
    "SCHEMA_KEYS",
    "SCHEMA_TYPES",
    "Tool",
    "ToolRegistry",
    "ToolSideEffect",
    "ToolValidationError",
    "VALIDATION_PROJECTION_KEYS",
    "ValidationResult",
    "can_transition",
    "canonical_record_bytes",
    "capability_entry",
    "canonical_descriptor_bytes",
    "canonical_schema_bytes",
    "check",
    "check_consistency",
    "consistency_report",
    "default_profiles",
    "get_default_profile",
    "manifest_capability_allowed",
    "mcp_to_tool",
    "orphan_agent_capabilities",
    "plan_fingerprint",
    "record_fingerprint",
    "redact_record",
    "resolve_capability",
    "unmapped_mvp_capabilities",
    "tool_to_mcp",
    "validate_record",
    "validate_plan",
    "validate_policy",
    "validate_schema",
    "validate_tool",
    "validate_transition_path",
    "write_memory",
]
